### ISSUE TITLE
Awesome work !

### ISSUE THREAD

**Issue by Nosenzor** [IOdissey/bfgs#1]
Thanks a lot for your work. Easy to use and efficient !
I just had to fix the log10 and log2 function in dval.h
At least on my computer (Apple with clang, the constexpr k does not compile, I think because std::log has not been "constexprefied" by Apple :-( )

const auto OneOnlog10=1.0 / std::log(10.0);
	template <uint32_t N>
	inline DVal<N> log10(const DVal<N>& x)
	{
		DVal<N> dval(x, false);
		dval.d[0] = std::log10(x.d[0]);
        double k = OneOnlog10;//1.0 / std::log(10.0);
		const double c = k / x.d[0];
		const uint32_t nn = x.n();
		for (uint32_t i = 1; i < nn; ++i)
			dval.d[i] = x.d[i] * c;
		return dval;
	}
    const auto OneOnlog2=1.0 / std::log(2.0);
	template <uint32_t N>
	inline DVal<N> log2(const DVal<N>& x)
	{
		DVal<N> dval(x, false);
		dval.d[0] = std::log2(x.d[0]);
        double k = OneOnlog2;//1.0 / std::log(2.0);
		const double c = k / x.d[0];
		const uint32_t nn = x.n();
		for (uint32_t i = 1; i < nn; ++i)
			dval.d[i] = x.d[i] * c;
		return dval;
	}

**Comment by IOdissey** [comment]
Hello.
I'm glad it works!
Unfortunately I don't have an apple computer to check. Perhaps this can be solved with compilation flags, for example -std=c++11 or -std=c++17 (not sure what standard is needed).

In file CmakeLists.txt is a commented line:
```
# set(CMAKE_CXX_STANDARD 14)
```

If automatic derivatives are not needed, the dval.h and memory.h files can be excluded from the project. In the bfgs.h file remove includes and `find_min_auto` functinons.

**Comment by Nosenzor** [comment]
Also it seems the dimension argument should be part of a template parameter (or should be a constexpr): some compiler don't like it (complaining about DVal<0> dval[n]) :
Maybe change something like
double find_min_auto(const std::function<DVal<0> (DVal<0>*, uint32_t)>& f, double* const x, const uint32_t n){
	...
			
		return find_min(g, x, n);
	}
should be turned into 
template<const int n>
	double find_min_auto(const std::function<DVal<0> (DVal<0>*, uint32_t)>& f, double* const x){
	...
			
		return find_min<n>(g, x);
	}

**Comment by Nosenzor** [comment]
I will try to send you my changes

**Comment by IOdissey** [comment]
Hello!
Thank you for your comment.

Yes, the parameter n must be calculated at compile time. But the gcc compiler (Ubuntu) ate it, and I just forgot about it.

I fix it (I hope).

In general, the whole part with automatic derivatives is rather experimental. Often it works no faster than numerical differentiation.

P.S. I also added the BFGS_NO_AUTO macro to disable the automatic derivatives part if it is not needed.
